<a href="https://colab.research.google.com/github/meetAmarAtGithub/15_Reva_Speech_Analytics/blob/main/Sesssion_3_Leg_Speech_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Simple Speech Recognition


In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [9]:
%cd "/content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/"

/content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset


In [2]:
!pip install pyAudioAnalysis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 MB 8.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyAudioAnalysis: filename=pyAudioAnalysis-0.3.14-py3-none-any.whl size=41264374 sha256=0f9c20ab7810820fc05f221abade3f4211737c5dad94581178420635e80213fb
  Stored in directory: /root/.cache/pip/wheels/a7/54/73/fa830689c2440d2c81ff175c60e374930ad1607a8881e0f43f
Successfully built pyAudioAnalysis


In [3]:
!pip install eyed3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.1/246.1 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.0/239.0 kB 26.8 MB/s eta 0:00:00


In [4]:
!pip install pydub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [52]:
#import the required files
from pyAudioAnalysis import MidTermFeatures as aF
import os
import numpy as np
from sklearn.svm import SVC
import plotly.graph_objs as go
import plotly

In [53]:
#Load the data
path = "/content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset"

In [54]:
dirs = [path+"/up/", path+"/down/"] 

In [55]:
class_names = ['up', 'down'] 
print(class_names)

['up', 'down']


In [56]:
#initialize minimu window, minimum step, window size and step size
m_win, m_step, s_win, s_step = 1, 1, 0.1, 0.05

In [57]:
# segment-level feature extraction:
features = [] 

In [58]:
features = [] 
for d in dirs: # get feature matrix for each directory (class)
    print(d)
    f, files, fn = aF.directory_feature_extraction(d, m_win, m_step, 
                                                   s_win, s_step) 
    features.append(f)

/content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/
Analyzing file 1 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0ab3b47d_nohash_0.wav
Analyzing file 2 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0ac15fe9_nohash_0.wav
Analyzing file 3 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0b40aa8e_nohash_1.wav
Analyzing file 4 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0c5027de_nohash_1.wav
Analyzing file 5 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0d2bcf9d_nohash_0.wav
Analyzing file 6 of 6: /content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/speech recognition mini dataset/up/0d2bcf9d_nohash_1.wav
Feature extraction com

In [59]:
features

[array([[ 8.60120909e-02,  2.47440034e-02,  2.53891120e+00,
          2.99563121e-01,  2.50476527e-01,  1.06079218e+00,
          3.12751062e-03,  1.76000000e-01, -3.19376197e+01,
          6.17611764e-01, -7.42737414e-01,  2.79366910e-01,
          1.54879551e-01,  1.12555598e-01,  1.79155084e-01,
         -2.73185029e-01,  1.78320909e-01,  5.06723897e-02,
         -6.87264045e-02,  6.62465027e-02, -7.67686270e-02,
          2.78384998e-03,  2.44667866e-03,  8.73647457e-02,
          2.62152492e-03,  3.94828755e-03,  1.98358846e-03,
          3.78439185e-03,  2.35912490e-03,  3.81848955e-03,
          4.11877234e-03,  3.29353544e-03,  1.62358451e-03,
          2.45511902e-02,  6.25390869e-03,  3.94315994e-07,
         -7.93258779e-02, -1.17204382e-02, -6.53485513e-03,
          6.68877177e-02,  1.15047178e-04,  7.50000000e-04,
          3.54155817e-01, -3.95834863e-02, -5.27020820e-02,
          5.95714929e-04, -1.61737243e-02,  6.21250736e-04,
          4.42240843e-02, -3.55433659e-0

In [60]:
print(features[0].shape, features[1].shape)

(6, 138) (10, 138)


In [61]:
# select 2 features and create feature matrices for the two classes:
f1 = np.array([features[0][:, fn.index('spectral_centroid_mean')],
               features[0][:, fn.index('energy_entropy_mean')]])

In [62]:
f2 = np.array([features[1][:, fn.index('spectral_centroid_mean')],
               features[1][:, fn.index('energy_entropy_mean')]])

In [63]:
# select 2 features and create feature matrices for the two classes:
f1 = np.array([features[0][:, fn.index('spectral_centroid_mean')],
               features[0][:, fn.index('energy_entropy_mean')]])
f2 = np.array([features[1][:, fn.index('spectral_centroid_mean')],
               features[1][:, fn.index('energy_entropy_mean')]])

In [64]:
# plot 2D features
p1 = go.Scatter(x=f1[0, :],  y=f1[1, :], name=class_names[0],
                marker=dict(size=10,color='rgba(255, 182, 193, .9)'),
                mode='markers')
p2 = go.Scatter(x=f2[0, :], y=f2[1, :],  name=class_names[1], 
                marker=dict(size=10,color='rgba(100, 100, 220, .9)'),
                mode='markers')
mylayout = go.Layout(xaxis=dict(title="spectral_centroid_mean"),
                     yaxis=dict(title="energy_entropy_mean"))

y = np.concatenate((np.zeros(f1.shape[1]), np.ones(f2.shape[1]))) 
f = np.concatenate((f1.T, f2.T), axis = 0)

In [65]:
# train the svm classifier
cl = SVC(kernel='rbf', C=20) 
cl.fit(f, y) 

SVC(C=20)

In [66]:
from sklearn.metrics import confusion_matrix

y_pred = cl.predict(f)
confusion_matrix(y, y_pred)

array([[4, 2],
       [2, 8]])

In [67]:
# Classify an unknown sample (song)
from pyAudioAnalysis import audioTrainTest as aT
file1 = "/content/gdrive/My Drive/Colab Notebooks/Reva/15_Speech_Analytics/AudioFiles/classical/data_music_classical_classical.00012.au.wav"

In [68]:
#Prepocess into features
from pyAudioAnalysis import MidTermFeatures as aF
from pyAudioAnalysis import audioBasicIO as aIO 

# read audio data from file 
# (returns sampling freq and signal as a numpy array)
fs, s = aIO.read_audio_file(file1)

# get mid-term (segment) feature statistics 
# and respective short-term features:
mt, st, mt_n = aF.mid_feature_extraction(s, fs, 1 * fs, 1 * fs, 0.05 * fs, 0.05 * fs)

In [69]:
print(mt)

[[ 1.76190476e-01  1.83959900e-01]
 [ 7.63419523e-02  4.23456104e-02]
 [ 3.20161356e+00  3.19009134e+00]
 [ 2.42782639e-01  2.82885997e-01]
 [ 2.03396682e-01  2.37286138e-01]
 [ 1.68341334e+00  1.32856322e+00]
 [ 5.09442344e-03  8.26115928e-03]
 [ 2.80750000e-01  2.94250000e-01]
 [-2.17494087e+01 -2.38171243e+01]
 [ 2.23091755e+00  1.54395897e+00]
 [-7.42801346e-01 -6.46177574e-01]
 [-2.55080129e-01 -8.60804467e-01]
 [-6.50692566e-01 -5.68847114e-01]
 [-2.75907950e-02  3.11351423e-01]
 [-2.85582206e-01  3.62129980e-01]
 [ 4.37441608e-01  6.06176309e-01]
 [ 3.28315765e-01 -6.22075343e-03]
 [-2.50633135e-01 -4.13670017e-01]
 [-1.04403137e-01  6.74359796e-02]
 [ 5.42583685e-02  3.06882203e-01]
 [ 1.83362851e-01  8.84742827e-02]
 [ 1.79546963e-02  9.34039727e-03]
 [ 3.08985846e-02  3.90070399e-02]
 [ 5.32363517e-03  5.25062938e-03]
 [ 1.66054840e-02  9.54462983e-03]
 [ 1.98749519e-02  2.64048972e-02]
 [ 4.69843364e-03  3.30743507e-02]
 [ 3.95107502e-03  1.35554770e-02]
 [ 6.08213340e-04  1

In [70]:
print(f1)

[[0.29956312 0.3437801  0.2558271  0.26613944 0.22816708 0.22383993]
 [2.5389112  3.00137613 2.59955886 2.53272293 2.82402497 2.68315853]]


In [71]:
# select 2 features and create feature matrices for the two classes:
f = np.array(mt[:1, ])

In [72]:
cl.predict(f)

array([0.])

## KNN classifier

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
knn = KNeighborsClassifier(n_neighbors=1)

In [75]:
y = np.concatenate((np.zeros(f1.shape[1]), np.ones(f2.shape[1]))) 
f = np.concatenate((f1.T, f2.T), axis = 0)

In [76]:
knn.fit(f,y)

KNeighborsClassifier(n_neighbors=1)

In [77]:
# select 2 features and create feature matrices for the two classes:
fknn = np.array(mt[:1, ])

In [78]:
class_names[int(knn.predict(fknn)[0])]

'up'

In [79]:
y_pred = knn.predict(f)
confusion_matrix(y, y_pred)

array([[ 6,  0],
       [ 0, 10]])

## Gaussian Naive Bayes

In [80]:
from sklearn.naive_bayes import GaussianNB

In [81]:
nb = GaussianNB()

In [82]:
nb.fit(f, y)

GaussianNB()

In [84]:
y_pred = nb.predict(f)
confusion_matrix(y, y_pred)

array([[4, 2],
       [2, 8]])

## Random Forest Clasifier

In [86]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
rf = RandomForestClassifier()

In [88]:
rf.fit(f, y)

RandomForestClassifier()

In [89]:
y_pred = rf.predict(f)
confusion_matrix(y, y_pred)

array([[ 6,  0],
       [ 0, 10]])